version: "3"
services:
  web:
    build: .
    command: bash -c "bundle check || bundle install && bundle exec rerun --background 'rackup --host 0.0.0.0 -p 10009' 1>/dev/null"
    ports:
      - "10009:10009"
    environment:
      LANG: "C.UTF-8"
      LC_ALL: "C.UTF-8"
    volumes:
      - .:/usr/src/app
      - ./.bundle:/usr/local/bundle
  db:
    # use latest official postgres version
    image: postgres
    env_file:
      - config/database.env
    # persist data even if container shuts down
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
     # use latest official postgres version
  testdb:
    image: postgres
    env_file:
      - config/database.test.env

volumes:
  postgres-data:

